<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="VerTurnos.aspx.cs" Inherits="Vistas.VerTurnos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Ver turnos</title>

</head>
<body class="container d-flex position-relative bg-info bg-opacity-75" style="max-height: 100%; height: 720px; left: 0px; top: 0px;">
    <form id="form1" runat="server">

          <div class="dropdown position-absolute  top-0 end-0 mt-2" id="botonCerrarSesion">
                  <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <asp:Label ID="lblUsuario" runat="server" Text=""></asp:Label>
                  </button>
                  <ul class="dropdown-menu">
                    <li class="text-center text-decoration-none"> <asp:LinkButton ID="lbtnCerrarSesion"  runat="server" OnClick="lbtnCerrarSesion_Click">Cerrar Sesion</asp:LinkButton></li>
                  </ul>
            </div> 
                     <asp:HyperLink ID="hlVolverSubMenuTurnos" runat="server"  CssClass=" btn btn-light text-decoration-none text-dark  position-absolute  top-0 start-0 mt-2"  Font-Underline="True" ForeColor="Blue" NavigateUrl="~/MenuPrincipal.aspx">Volver a Menu principal</asp:HyperLink>


           <div class=" w-75 bg-light mt-4 p-3 m border rounded-2 justify-content-center align-items-center  position-absolute top-50 start-50 translate-middle">
                 <asp:Label ID="Label0" runat="server" CssClass="d-block text-center my-3 mb-5" Font-Bold="True" Font-Size="X-Large" Text="TURNOS"></asp:Label>


               <div  class="d-flex justify-content-center align-item-center">
                   <div class="w-50">
                       <asp:Label ID="lblBuscarNombre"  runat="server" Text="Filtrar por nombre o especialidad:"></asp:Label>
                       <asp:TextBox ID="txtNombreVerTurnos" runat="server"></asp:TextBox>
                   </div>
                   <div class="w-50">
                       <asp:Label ID="lblBuscarFecha" runat="server" Text="Filtrar por fecha (d/m/aaaa):"></asp:Label>
                       <asp:TextBox ID="txtFechaVerTurnos" runat="server"></asp:TextBox>
                       <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtFechaVerTurnos" ErrorMessage="*Formato fecha incorrecto " ForeColor="Red" ValidationExpression="^([1-9]|[12][0-9]|3[01])[/-]([1-9]|1[012])[/-]\d{4}$" ValidationGroup="grp1"></asp:RegularExpressionValidator>
                   </div>
                </div>

               <div class="d-flex justify-content-around align-item-center">
                  <div>
                   <asp:Label ID="lblBuscarHorario" runat="server" Text="Filtrar por horario:&nbsp;"></asp:Label>
                   <asp:DropDownList ID="ddlHorarios" runat="server">
                   </asp:DropDownList>

                   </div>
                   <div>
                        <asp:Label ID="lblPendientes" runat="server" Text="Filtrar por turnos pendientes:"></asp:Label>
                   <asp:RadioButton ID="rbtnPendientes" runat="server" />
                   </div>
                   <div>
                        <asp:Button ID="btnFiltrarVerTurnos" runat="server" Text="Filtrar" OnClick="btnFiltrarVerTurnos_Click" ValidationGroup="grp1" CssClass=" btn text-light bg-info" />
                    <asp:Button ID="btnTodosVerTurnos" runat="server" CssClass=" btn bg-danger text-light" OnClick="btnTodosVerTurnos_Click" Text="Ver todos" />
                   </div>

               </div>
               
                   
                    
                   
              
                    <asp:Label ID="lblMensajeVerTurnos" runat="server" Visible="False"></asp:Label>
                
                    <asp:GridView ID="grdVerTurnos" runat="server"  CssClass="table  table-striped p-3 my-4" AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="grdVerTurnos_PageIndexChanging" OnRowDeleting="grdVerTurnos_RowDeleting" PageSize="6" AutoGenerateSelectButton="True" OnSelectedIndexChanging="grdVerTurnos_SelectedIndexChanging">
                    </asp:GridView>
                    <asp:HyperLink ID="hlConsulta" runat="server" CssClass="btn bg-success w-50 mx-auto d-block  text-light" NavigateUrl="~/CompletarConsulta.aspx" Visible="False">Completar Consulta</asp:HyperLink>
              


               <div class=" mt-4 w-100  p-3 mx-auto d-flex justify-content-center align-items-center">
                <asp:Label ID="lblConfirmacion" runat="server" CssClass="me-4" Text="¿Esta seguro que quiere eliminar este horario?" Visible="False"></asp:Label>

                <asp:LinkButton ID="lbSi" runat="server" OnClick="lbSi_Click" CssClass="btn btn-success" Visible="False">SI</asp:LinkButton>

                <asp:LinkButton ID="lbNo" runat="server"  CssClass="btn btn-danger ms-3"  OnClick="lbNo_Click" Visible="False">NO</asp:LinkButton>
            </div>

               
                  
                            
               
           </div>


    </form>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>
